# -*- coding: utf-8 -*-
"""DlLab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGRhgQLnLjXwQq8rD_ckpEN7l4mk5t86
"""

import torch
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import Trainer, TrainingArguments
from datasets import Dataset
import pandas as pd

# 🔹 Load your IMDB dataset
df = pd.read_csv(
    "/content/IMDB Dataset.csv",
    engine="python",
    on_bad_lines="skip"
)
# Convert labels
df['label'] = df['sentiment'].map({'positive': 1, 'negative': 0})
df = df[['review', 'label']]

# Use small subset (for demo)
df = df.sample(2000, random_state=42)

dataset = Dataset.from_pandas(df)

# 🔹 Tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize(example):
    return tokenizer(example['review'], truncation=True, padding='max_length', max_length=128)

dataset = dataset.map(tokenize, batched=True)

dataset = dataset.train_test_split(test_size=0.2)

# 🔹 Model
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

# 🔹 Training args
training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    logging_dir="./logs",
)

# 🔹 Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset['train'],
    eval_dataset=dataset['test'],
)

# 🔹 Train
trainer.train()

# 🔹 Test prediction
inputs = tokenizer("This movie was amazing!", return_tensors="pt")
outputs = model(**inputs)

pred = torch.argmax(outputs.logits, dim=1).item()

print("Prediction:", "Positive " if pred == 1 else "Negative ")